"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MoveUnitRandomly = exports.MoveToTileToImprove = exports.MoveToGoodSiteForCity = exports.MoveToExploreMap = exports.MoveToDefendCity = exports.ImproveTile = exports.FortifyDefender = exports.DoNothingWithUnit = exports.ContinueOnPath = exports.ChooseResearchFromList = exports.ChooseResearch = exports.CheckForUndefendedCities = exports.ChangeGovernment = exports.BuyDefender = exports.BuildSettlers = exports.BuildNavalTransportForLandUnits = exports.BuildNavalTransportForAirUnits = exports.BuildExplorer = exports.BuildDefender = exports.BuildCity = void 0;
var BuildCity_1 = require("./Strategies/BuildCity");
Object.defineProperty(exports, "BuildCity", { enumerable: true, get: function () { return BuildCity_1.BuildCity; } });
var BuildDefender_1 = require("./Strategies/BuildDefender");
Object.defineProperty(exports, "BuildDefender", { enumerable: true, get: function () { return BuildDefender_1.BuildDefender; } });
var BuildExplorer_1 = require("./Strategies/BuildExplorer");
Object.defineProperty(exports, "BuildExplorer", { enumerable: true, get: function () { return BuildExplorer_1.BuildExplorer; } });
var BuildNavalTransportForAirUnits_1 = require("./Strategies/BuildNavalTransportForAirUnits");
Object.defineProperty(exports, "BuildNavalTransportForAirUnits", { enumerable: true, get: function () { return BuildNavalTransportForAirUnits_1.BuildNavalTransportForAirUnits; } });
var BuildNavalTransportForLandUnits_1 = require("./Strategies/BuildNavalTransportForLandUnits");
Object.defineProperty(exports, "BuildNavalTransportForLandUnits", { enumerable: true, get: function () { return BuildNavalTransportForLandUnits_1.BuildNavalTransportForLandUnits; } });
var BuildSettlers_1 = require("./Strategies/BuildSettlers");
Object.defineProperty(exports, "BuildSettlers", { enumerable: true, get: function () { return BuildSettlers_1.BuildSettlers; } });
var BuyDefender_1 = require("./Strategies/BuyDefender");
Object.defineProperty(exports, "BuyDefender", { enumerable: true, get: function () { return BuyDefender_1.BuyDefender; } });
var ChangeGovernment_1 = require("./Strategies/ChangeGovernment");
Object.defineProperty(exports, "ChangeGovernment", { enumerable: true, get: function () { return ChangeGovernment_1.ChangeGovernment; } });
var CheckForUndefendedCities_1 = require("./Strategies/CheckForUndefendedCities");
Object.defineProperty(exports, "CheckForUndefendedCities", { enumerable: true, get: function () { return CheckForUndefendedCities_1.CheckForUndefendedCities; } });
var ChooseResearch_1 = require("./Strategies/ChooseResearch");
Object.defineProperty(exports, "ChooseResearch", { enumerable: true, get: function () { return ChooseResearch_1.ChooseResearch; } });
var ChooseResearchFromList_1 = require("./Strategies/ChooseResearchFromList");
Object.defineProperty(exports, "ChooseResearchFromList", { enumerable: true, get: function () { return ChooseResearchFromList_1.ChooseResearchFromList; } });
var ContinueOnPath_1 = require("./Strategies/ContinueOnPath");
Object.defineProperty(exports, "ContinueOnPath", { enumerable: true, get: function () { return ContinueOnPath_1.ContinueOnPath; } });
var DoNothingWithUnit_1 = require("./Strategies/DoNothingWithUnit");
Object.defineProperty(exports, "DoNothingWithUnit", { enumerable: true, get: function () { return DoNothingWithUnit_1.DoNothingWithUnit; } });
var FortifyDefender_1 = require("./Strategies/FortifyDefender");
Object.defineProperty(exports, "FortifyDefender", { enumerable: true, get: function () { return FortifyDefender_1.FortifyDefender; } });
var ImproveTile_1 = require("./Strategies/ImproveTile");
Object.defineProperty(exports, "ImproveTile", { enumerable: true, get: function () { return ImproveTile_1.ImproveTile; } });
var MoveToDefendCity_1 = require("./Strategies/MoveToDefendCity");
Object.defineProperty(exports, "MoveToDefendCity", { enumerable: true, get: function () { return MoveToDefendCity_1.MoveToDefendCity; } });
var MoveToExploreMap_1 = require("./Strategies/MoveToExploreMap");
Object.defineProperty(exports, "MoveToExploreMap", { enumerable: true, get: function () { return MoveToExploreMap_1.MoveToExploreMap; } });
var MoveToGoodSiteForCity_1 = require("./Strategies/MoveToGoodSiteForCity");
Object.defineProperty(exports, "MoveToGoodSiteForCity", { enumerable: true, get: function () { return MoveToGoodSiteForCity_1.MoveToGoodSiteForCity; } });
var MoveToTileToImprove_1 = require("./Strategies/MoveToTileToImprove");
Object.defineProperty(exports, "MoveToTileToImprove", { enumerable: true, get: function () { return MoveToTileToImprove_1.MoveToTileToImprove; } });
var MoveUnitRandomly_1 = require("./Strategies/MoveUnitRandomly");
Object.defineProperty(exports, "MoveUnitRandomly", { enumerable: true, get: function () { return MoveUnitRandomly_1.MoveUnitRandomly; } });
//# sourceMappingURL=Strategies.js.map